[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[functions."send-task-notifications"]
schedule = "0 * * * *"  # Every hour at the top of the hour 